# Simulation parameters
num_row: 5              # Number of SPAD rows
num_col: 5              # Number of SPAD cols
eta: 0.3057              # Detection efficiency
xtk: 0.05               # Crosstalk probability
iterations: 1e7         # Number of simulation iterations

# Dark count rate range
dcr_min: 1e-3           # Minimum dark count rate
dcr_max: 1e-2           # Maximum dark count rate

# Photon distribution settings
# options: "poisson", "thermal" or "discrete"
photon_distribution:
  type: "poisson"
  mean: 4.95

# photon_distribution:
#   type: "thermal"
#   mean: 4.93

# photon_distribution:
#   type: "discrete"
#   probabilities: [0.45, 0.55]

# EME solver settings
alpha: 1e-2
